CrashDumpsConfigure/README.md

CrashDumpsConfigure README fix to correct header sizes
- Bug fix

CrashDumpsConfigure README fix

---

README.md
Templates/hardware-readme-template.md
Templates/software-readme-template.md

Adding a template readme for hardware projects, and a few minor fixes

Add template readme for HW projects

---

.github/pull_request_template.md
README.md

Add project index to repo-level readme and update PR template to refer to it

Add project index to repo-level readme

---

DeviceTenantFinder/LICENSE.txt
DeviceTenantFinder/README.md
DeviceTenantFinder/Src/DeviceTenantFinder.sln
DeviceTenantFinder/Src/DeviceTenantFinder/DeviceTenantFinder.csproj
DeviceTenantFinder/Src/DeviceTenantFinder/Program.cs
DeviceTenantFinder/Src/DeviceTenantFinder/Properties/launchSettings.json
README.md

Initial check in for Device Tenant Finder utility that makes it easy to find the Azure Sphere tenant name/Id within your tenants for a given Device Id
- New content

Initial check in for Device Tenant Finder

---

README.md
SetTimeFromLocation/LICENSE.txt
SetTimeFromLocation/README.md
SetTimeFromLocation/src/.vscode/launch.json
SetTimeFromLocation/src/.vscode/settings.json
SetTimeFromLocation/src/CMakeLists.txt
SetTimeFromLocation/src/CMakeSettings.json
SetTimeFromLocation/src/app_manifest.json
SetTimeFromLocation/src/applibs_versions.h
SetTimeFromLocation/src/httpGet.c
SetTimeFromLocation/src/httpGet.h
SetTimeFromLocation/src/launch.vs.json
SetTimeFromLocation/src/location_from_ip.c
SetTimeFromLocation/src/location_from_ip.h
SetTimeFromLocation/src/main.c
SetTimeFromLocation/src/parson.c
SetTimeFromLocation/src/parson.h
SetTimeFromLocation/src/settime.c
SetTimeFromLocation/src/settime.h

Project that shows how to use reverse ip lookup to obtain location, then obtaining time for location, and setting device time.
- New content

initial check in for SetTimeForLocation

---

OSNetworkRequirementChecker-PC/.gitignore
OSNetworkRequirementChecker-PC/LICENSE.txt
OSNetworkRequirementChecker-PC/OSNetworkRequirementChecker-PC.sln
OSNetworkRequirementChecker-PC/OSNetworkRequirementChecker-PC.vcxproj
OSNetworkRequirementChecker-PC/README.md
OSNetworkRequirementChecker-PC/main.cpp
README.md

Initial commit.
A PC command line utility for diagnosing networking connectivity issues.
- New content

Added OSNetworkRequirementChecker-PC tool.

---

MultiDeviceProvisioning/LICENSE.txt
MultiDeviceProvisioning/README.md
MultiDeviceProvisioning/provision.py
MultiDeviceProvisioning/provision_deleteapps.py
MultiDeviceProvisioning/provision_wifi.py
README.md

Python script that shows how multiple Azure Sphere devices can be provisioned automatically and simultaneously from a single PC
- New content

device provisioning project

---

README.md
WifiConfigurationViaUart/LICENSE.txt
WifiConfigurationViaUart/README.md
WifiConfigurationViaUart/src/.vscode/launch.json
WifiConfigurationViaUart/src/.vscode/settings.json
WifiConfigurationViaUart/src/CMakeLists.txt
WifiConfigurationViaUart/src/CMakeSettings.json
WifiConfigurationViaUart/src/SerialWiFiConfig.c
WifiConfigurationViaUart/src/SerialWiFiConfig.h
WifiConfigurationViaUart/src/app_manifest.json
WifiConfigurationViaUart/src/applibs_versions.h
WifiConfigurationViaUart/src/eventloop_timer_utilities.c
WifiConfigurationViaUart/src/eventloop_timer_utilities.h
WifiConfigurationViaUart/src/launch.vs.json
WifiConfigurationViaUart/src/main.c

Project that shows how to configure a device wifi settings via uart.
- New content

add WifiConfigurationViaUart project

---

BalancingRobot/README.md

Update Balancing Robot README.md

---

README.md
WifiConfigurationViaAppResource/LICENSE.txt
WifiConfigurationViaAppResource/README.md
WifiConfigurationViaAppResource/ThirdPartyNotices.txt
WifiConfigurationViaAppResource/src/.vscode/launch.json
WifiConfigurationViaAppResource/src/.vscode/settings.json
WifiConfigurationViaAppResource/src/AppResourceWiFiConfig.c
WifiConfigurationViaAppResource/src/AppResourceWiFiConfig.h
WifiConfigurationViaAppResource/src/CMakeLists.txt
WifiConfigurationViaAppResource/src/CMakeSettings.json
WifiConfigurationViaAppResource/src/WiFiConfig.json
WifiConfigurationViaAppResource/src/app_manifest.json
WifiConfigurationViaAppResource/src/applibs_versions.h
WifiConfigurationViaAppResource/src/launch.vs.json
WifiConfigurationViaAppResource/src/main.c
WifiConfigurationViaAppResource/src/parson.c
WifiConfigurationViaAppResource/src/parson.h

Project that shows how to set wifi configuration using an embedded JSON resource file
- New content

WifiConfigurationViaAppResource project

---

AzureSphereTenantDeviceTwinSync/src/REST_API/AzureSphereTenantDeviceTwinSync/Utils.cs

Update for HTTP Get code to fix calls to non AS3 endpoints
- Bug fix

Update http get code

---

.gitmodules
MQTT-C_Client/LICENSE.txt
MQTT-C_Client/README.md
MQTT-C_Client/src/HighLevelApp/.vscode/launch.json
MQTT-C_Client/src/HighLevelApp/.vscode/settings.json
MQTT-C_Client/src/HighLevelApp/CMakeLists.txt
MQTT-C_Client/src/HighLevelApp/CMakeSettings.json
MQTT-C_Client/src/HighLevelApp/app_manifest.json
MQTT-C_Client/src/HighLevelApp/applibs_versions.h
MQTT-C_Client/src/HighLevelApp/comms_manager.c
MQTT-C_Client/src/HighLevelApp/comms_manager.h
MQTT-C_Client/src/HighLevelApp/launch.vs.json
MQTT-C_Client/src/HighLevelApp/main.c
MQTT-C_Client/src/PyMqttHost/PyMqttHost.py
MQTT-C_Client/src/PyMqttHost/requirements.txt
README.md

MQTT-C Azure Sphere Sample
- New content

MQTT-C Library sample

---

Grove_16x2_RGB_LCD/src/main.c

modify the backlight for loop to fix build warning
- Bug fix

update to main, fix build warning

---

README.md
TranslatorCognitiveServices/LICENSE.txt
TranslatorCognitiveServices/README.md
TranslatorCognitiveServices/src/.vscode/launch.json
TranslatorCognitiveServices/src/.vscode/settings.json
TranslatorCognitiveServices/src/CMakeLists.txt
TranslatorCognitiveServices/src/CMakeSettings.json
TranslatorCognitiveServices/src/app_manifest.json
TranslatorCognitiveServices/src/applibs_versions.h
TranslatorCognitiveServices/src/launch.vs.json
TranslatorCognitiveServices/src/main.c
TranslatorCognitiveServices/src/parson.c
TranslatorCognitiveServices/src/parson.h
TranslatorCognitiveServices/src/translator.c
TranslatorCognitiveServices/src/translator.h

Project that shows how to use the Microsoft Translator Cognitive Services APIs from an Azure Sphere High Level application
- New content

Translator Cognitive Services project

---

README.md
WiFiConfigurationViaNfc/LICENSE.txt
WiFiConfigurationViaNfc/README.md
WiFiConfigurationViaNfc/src/.vscode/launch.json
WiFiConfigurationViaNfc/src/.vscode/settings.json
WiFiConfigurationViaNfc/src/CMakeLists.txt
WiFiConfigurationViaNfc/src/CMakeSettings.json
WiFiConfigurationViaNfc/src/M24SR/M24SR.c
WiFiConfigurationViaNfc/src/M24SR/M24SR.h
WiFiConfigurationViaNfc/src/app_manifest.json
WiFiConfigurationViaNfc/src/applibs_versions.h
WiFiConfigurationViaNfc/src/eventloop_timer_utilities.c
WiFiConfigurationViaNfc/src/eventloop_timer_utilities.h
WiFiConfigurationViaNfc/src/launch.vs.json
WiFiConfigurationViaNfc/src/main.c
WiFiConfigurationViaNfc/src/utils.c
WiFiConfigurationViaNfc/src/utils.h

Project that shows how to configure device WiFi using NFC
- New content

WiFi configuration via Nfc

---

WiFiConfigurationViaNfc/src/M24SR/M24SR.c

Fix for iPhone 'NFC Tools' NDEF Record format, add retry on I2C Writes, and fix Deselect to enable multi-tap.
- Bug fix

parse iPhone WiFi NDEF records, add I2C Retry, and fix multi-tap

---

AzureIoTMessageWithProperties/LICENSE.txt
AzureIoTMessageWithProperties/README.md
AzureIoTMessageWithProperties/src/HighLevelApp/common/azure_iot.c
AzureIoTMessageWithProperties/src/HighLevelApp/common/azure_iot.h
AzureIoTMessageWithProperties/src/HighLevelApp/common/cloud.c
README.md

A project that demonstrates how to add custom properties to an Azure IoT telemetry message and then use the properties for custom routing in Azure IoT Hub.
- New content

AzureIoTMessageWithProperties Project

---

OSNetworkRequirementChecker-PC/main.cpp

Please include a summary of the change.
Added socket timeout in query_ntp_server().
- [X ] My content has a file named README.md, which is based on the appropriate readme [template](https://github.com/Azure/azure-sphere-gallery/tree/main/Templates)
- [X ] I have performed a self-review of my own contribution
- [X ] I have provided comments where appropriate
- [X ] I have updated the repository's [README.md](https://github.com/Azure/azure-sphere-gallery/blob/main/README.md) to index this project
- [X ] I have added/updated license(s) for this project as appropriate
- [X ] I have permission to publish this content (in case the content was collaborative)
- [X ] I have verified that my content does not contain sensitive …

Added socket timeout in query_ntp_server()

---

OSNetworkRequirementChecker-PC/README.md
OSNetworkRequirementChecker-PC/main.cpp

Updates to the list of NTP server IP addresses, minor logging improvements.
- [X ] My content has a file named README.md, which is based on the appropriate readme [template](https://github.com/Azure/azure-sphere-gallery/tree/main/Templates)
- [X ] I have performed a self-review of my own contribution
- [ X] I have provided comments where appropriate
- [ X] I have updated the repository's [README.md](https://github.com/Azure/azure-sphere-gallery/blob/main/README.md) to index this project
- [X ] I have added/updated license(s) for this project as appropriate
- [ X] I have permission to publish this content (in case the content was collaborative)
- [X ] I have verified that my content does not contain sensitive …

Updates to the list of NTP server IP addresses

---

NetworkInterfaceAddresses/.vscode/launch.json
NetworkInterfaceAddresses/.vscode/settings.json
NetworkInterfaceAddresses/CMakeLists.txt
NetworkInterfaceAddresses/CMakeSettings.json
NetworkInterfaceAddresses/LICENSE.txt
NetworkInterfaceAddresses/README.md
NetworkInterfaceAddresses/app_manifest.json
NetworkInterfaceAddresses/applibs_versions.h
NetworkInterfaceAddresses/launch.vs.json
NetworkInterfaceAddresses/main.c
README.md

A minimal app to showcase printing of MAC and IP address of a given interface
- New content

App to print network interface addresses

---

README.md
SimpleFileSystem_RemoteDisk/LICENSE.txt
SimpleFileSystem_RemoteDisk/README.md
SimpleFileSystem_RemoteDisk/src/HighLevelApp/.vscode/launch.json
SimpleFileSystem_RemoteDisk/src/HighLevelApp/.vscode/settings.json
SimpleFileSystem_RemoteDisk/src/HighLevelApp/CMakeLists.txt
SimpleFileSystem_RemoteDisk/src/HighLevelApp/CMakeSettings.json
SimpleFileSystem_RemoteDisk/src/HighLevelApp/SimpleFs/sfs.c
SimpleFileSystem_RemoteDisk/src/HighLevelApp/SimpleFs/sfs.h
SimpleFileSystem_RemoteDisk/src/HighLevelApp/app_manifest.json
SimpleFileSystem_RemoteDisk/src/HighLevelApp/applibs_versions.h
SimpleFileSystem_RemoteDisk/src/HighLevelApp/curlFunctions.c
SimpleFileSystem_RemoteDisk/src/HighLevelApp/curlFunctions.h
SimpleFileSystem_RemoteDisk/src/HighLevelApp/launch.vs.json
SimpleFileSystem_RemoteDisk/src/HighLevelApp/main.c
SimpleFileSystem_RemoteDisk/src/HighLevelApp/remoteDiskIO.c
SimpleFileSystem_RemoteDisk/src/HighLevelApp/remoteDiskIO.h
SimpleFileSystem_RemoteDisk/src/PyDiskHost/PyDiskHost.py

Simple File System project (FIFO/Circular Buffer, up to 15 directories) with Python remote disk host application.
- New content

Simple File System

---

AzureIoT_StoreAndForward/LICENSE.txt
AzureIoT_StoreAndForward/README.md
AzureIoT_StoreAndForward/copy_required_files.cmd
AzureIoT_StoreAndForward/copy_required_files.sh
AzureIoT_StoreAndForward/src/CMakeLists.txt
AzureIoT_StoreAndForward/src/SimpleFileSystem/CMakeLists.txt
AzureIoT_StoreAndForward/src/common/exitcodes.h
AzureIoT_StoreAndForward/src/common/main.c
README.md

Project that adds telemetry store and forward capability to the AzureIoT Github sample project.
- New content

AzureIoT Telemetry Store and Forward project

---

AzureIoTMessageWithProperties/README.md
AzureSphereTenantDeviceTwinSync/README.md
DeviceTenantFinder/README.md
Grove_16x2_RGB_LCD/README.md
HeapTracker/README.md
LittleFs_RemoteDisk/README.md
LittleFs_SDCard/README.md
MQTT-C_Client/README.md
MutableStorageKVP/README.md
OSNetworkRequirementChecker-PC/README.md
SetIoTCentralPropsForDeviceGroup/README.md
SetTimeFromLocation/README.md
SimpleFileSystem_RemoteDisk/README.md
TranslatorCognitiveServices/README.md
UdpDebugLog/README.md
VS1053AudioStreaming/README.md
WebHookPublicAPIServicePrincipal/README.md
WiFiConfigurationViaNfc/README.md
WifiConfigurationViaAppResource/README.md
WifiConfigurationViaUart/README.md

fix license url for gallery projects
- Bug fix

update license url

---

OSNetworkRequirementChecker-HLApp/src/CMakeLists.txt
OSNetworkRequirementChecker-HLApp/src/dns-helper.c
OSNetworkRequirementChecker-PC/.gitignore
OSNetworkRequirementChecker-PC/main.cpp

Updated endpoint list.
Update to existing content

Updated endpoint list.

---

README.md
ToggleClassicCLI/LICENSE.txt
ToggleClassicCLI/Linux/ToggleClassicCLI.sh
ToggleClassicCLI/README.md
ToggleClassicCLI/Windows/ToggleClassicCLI.ps1

Scripts that enable testing of removal of the Azure Sphere Classic CLI
- New content

ToggleClassicCLI

---

AzureIoTMessageWithProperties/README.md
AzureIoT_StoreAndForward/README.md
AzureSphereTenantDeviceTwinSync/README.md
BalancingRobot/Software/HighLevelApp/README.md
SetIoTCentralPropsForDeviceGroup/README.md

Update readme.md files that point to the Azure Sphere App Samples repo

Updated links to Azure Sphere App Samples

---

RS485Driver/CMakeWorkspaceSettings.json

Adding top-level CMakeWorkspaceSettings.json, used by Visual Studio.
Update to existing content

Adding top-level CMakeWorkspaceSettings.json

---

DeviceTenantFinder/Src/DeviceTenantFinder.sln
DeviceTenantFinder/Src/DeviceTenantFinder/Program.cs

Update project to VS2022, fix output message for device not found
- Bug fix

Update project to VS2022, fix message for device not found
